Repository ERGA-consortium/EARs, pull requests merged in 2025-07, with the labels that each got.

#176 EAR upload of qmScyLatu1
  Assembly_Reports/Scyllarides_latus/qmScyLatu1/qmScyLatu1_EAR.pdf
Labels: ERGA-BGE

#182 EAR upload for qlOrcRanz
  Assembly_Reports/Orchesella ranzii/qlOrcRanz/qlOrcRanz_EAR.pdf
Labels: ERGA-BGE

#193 drAlcFaer1
  Assembly_Reports/Alchemilla_faeroensis/drAlcFaer1/drAlcFaer1_EAR.pdf
Labels: ERGA-BGE

#197 Add tolid folder for daAvefist1
  Assembly_Reports/Avellara_fistulosa/daAveFist1/daAveFist1_EAR.pdf
  Assembly_Reports/Avellara_fistulosa/daAveFist1/daAveFist1_EAR.yaml
Labels: ERROR!

#188 icCryBari1 EAR
  Assembly_Reports/Cryptocephalus_barii/icCryBari1/icCryBari1_EAR.pdf
Labels: ERGA-Pilot
